export {default as Footer} from './footer/Footer';
export {default as NavbarComp} from './navbarcomp/NavbarComp';
export {default as Who} from './who/Who';
export {default as Universities} from './universities/Universities';
export {default as Login} from './login/Login';
export {default as Signup} from './signup/Signup';
export {default as Register} from './register/Register';
export {default as Usernav} from './usernav/Usernav';
export {default as Userfoot} from './userfoot/Userfoot';