# Generated by Django 4.1.7 on 2023-02-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('uni_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('num_rsos', models.IntegerField()),
                ('description', models.CharField(max_length=140)),
                ('num_stu', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('loc_name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=512)),
                ('email', models.TextField(max_length=512)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RSOS',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('email', models.TextField(max_length=30)),
                ('event_type', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('loc_name', models.TextField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
                ('host_rso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=240)),
                ('rating', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.events')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.events')),
            ],
        ),
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Creates',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('creator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator1', to='application.users')),
                ('creator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator2', to='application.users')),
                ('creator3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator3', to='application.users')),
                ('creator4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator4', to='application.users')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Created_By',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.events')),
                ('name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.rsos')),
                ('uni_name', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='application.universities')),
            ],
        ),
    ]
