# Generated by Django 4.1.7 on 2023-04-06 19:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('uni_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('num_rsos', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(max_length=140)),
                ('num_stu', models.IntegerField(blank=True, default=0)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='00000000', max_length=512)),
                ('password', models.TextField(max_length=512)),
                ('email', models.TextField(max_length=512)),
                ('user_type', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.universities')),
            ],
        ),
        migrations.CreateModel(
            name='RSOS',
            fields=[
                ('rso_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pending', models.IntegerField(default=0)),
                ('admin', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(to='application.users')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.universities')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('email', models.TextField(max_length=30)),
                ('event_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('loc_name', models.TextField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
                ('host_rso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=240)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.events')),
            ],
        ),
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Creates',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('creator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator1', to='application.users')),
                ('creator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator2', to='application.users')),
                ('creator3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator3', to='application.users')),
                ('creator4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator4', to='application.users')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Created_By',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.events')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.users')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='application.rsos')),
                ('uni_name', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='application.universities')),
            ],
        ),
    ]
