# Generated by Django 4.1.7 on 2023-02-21 23:18

from django.db import migrations

def createData(apps, schema_editor):
    Users = apps.get_model('application', "Users")
    Users(user_id=1, password="password", email="user123@gmail.com", user_type=0)

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_user_id_belongs_user_and_more'),
    ]

    operations = [
        migrations.RunPython(createData)
    ]
