# Generated by Django 4.1.7 on 2023-02-21 23:24

from django.db import migrations

def createData(apps, schema_editor):
    Users = apps.get_model('application', 'Users')
    Users(user_id=1, password="password", email="user123@gmail.com", user_type=0)
    print("Hello World")


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20230221_2318'),
    ]

    operations = [
        migrations.RunPython(createData)
    ]
