# Generated by Django 4.1.7 on 2023-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20230221_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsos',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
