# Generated by Django 4.1.7 on 2023-03-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_users_name_alter_rsos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(default='00000000', max_length=512),
        ),
    ]
